version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: mosparking-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # PostgreSQL для будущей миграции (опционально)
  postgres:
    image: postgres:15-alpine
    container_name: mosparking-postgres
    environment:
      POSTGRES_DB: mosparking
      POSTGRES_USER: mosparking
      POSTGRES_PASSWORD: mosparking_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    profiles:
      - postgres

volumes:
  redis_data:
  postgres_data:
